name: Daily Push

on:
  schedule:
    - cron: '0 8 * * *'  # 每天 08:00 触发
  workflow_dispatch:  # 手动触发

jobs:
  push-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Push message
        run: node push-message.js
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_SECRET: ${{ secrets.APP_SECRET }}